### ISSUE TITLE
Installation instructions appear invalid in Django 3.1.5 w/Python3.8.x

### ISSUE THREAD

**Issue by dougglenn** [jlubcke/django-pycharm-breakpoint#2]
If I trying to add to the INSTALLED_APPS in the settings.py, it is unrecognized and produces an error.
Re: 
In settings.py add django-pycharm-breakpoint to your INSTALLED_APPS

```
INSTALLED_APPS += [‘django_pycharm_breakpoint’] (unresolved reference error)
```

Placing the ‘django_pycharm_breakpoint’ in the existing INSTALLED_APPS also generates a unresolved reference error

I've installed in the projects PyCharm packages as shown below.

```
Package                                 | version | latest version
Django                                   | 3.1.5     | 3.1.5
asgiref                                    | 3.3.1     | 3.3.1
django-pycharm-breakpoint   | 0.3.0     | 0.3.0
pip                                         | 20.3.3    | 20.3.3
pkg-resources                        | 0.0.0   
pytz                                       | 2020.5   | 2020.5
setuptools                             | 51.1.2    | 51.1.2
sqlparse                                | 0.4.1      | 0.4.1
```

Am I missing any other package it may require?

**Comment by jlubcke** [comment]
The instructions assume that you somewhere earlier in your settings.py has already defined an `INSTALLED_APPS` variable with the list of apps that django should load (My guess is that that is missing in your case, or is done later in the file). Either you add `'django_pycharm_breakpoint'` there, or in a separate statement appending to the list like in the instructions.

**Comment by dougglenn** [comment]
Working now. I must have fat fingered the entry.
Thank you for the quick response.

**Comment by dougglenn** [comment]
Issue Resolved
